// <auto-generated />
using System;
using ExpenseService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20260427015957_SeedExpensesTest1")]
    partial class SeedExpensesTest1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseService.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminApproved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HrApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AdminApproved = false,
                            Amount = 1250.00m,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("20000000-0000-0000-0000-000000000006"),
                            Currency = 1,
                            Description = "Ankara Müşteri Ziyareti",
                            HrApproved = false,
                            IsDeleted = false,
                            RequestedByUserId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Status = 1,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AdminApproved = false,
                            Amount = 450.00m,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("20000000-0000-0000-0000-000000000006"),
                            Currency = 1,
                            Description = "Kırtasiye Malzemeleri",
                            HrApproved = false,
                            IsDeleted = false,
                            RequestedByUserId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Status = 2,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AdminApproved = true,
                            Amount = 5000.00m,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("20000000-0000-0000-0000-000000000006"),
                            Currency = 1,
                            Description = "Udemy Eğitim Kursu",
                            HrApproved = true,
                            IsDeleted = false,
                            RequestedByUserId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Status = 3,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AdminApproved = false,
                            Amount = 200.00m,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("20000000-0000-0000-0000-000000000005"),
                            Currency = 2,
                            Description = "Yazılım Lisansı",
                            HrApproved = false,
                            IsDeleted = false,
                            RejectionReason = "Bütçe onayı yok",
                            RequestedByUserId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Status = 4,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AdminApproved = false,
                            Amount = 5500.00m,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("20000000-0000-0000-0000-000000000006"),
                            Currency = 1,
                            Description = "İstanbul Uçak Bileti",
                            HrApproved = true,
                            IsDeleted = false,
                            RequestedByUserId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Status = 2,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.ExpenseApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseApprovals");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredAt");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "izometri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "test1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "test2"
                        });
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "İzometri Admin",
                            Email = "admin@izometri.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "İzometri İK",
                            Email = "hr@izometri.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "İzometri Personel",
                            Email = "personel@izometri.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Test1 Admin",
                            Email = "pattabanoglu@devrimmehmet.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            Phone = "905438194976",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Test1 İK",
                            Email = "devrimmehmet@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            Phone = "905393649361",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Test1 Personel",
                            Email = "devrimmehmet@msn.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Test2 Admin",
                            Email = "admin@test2.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Test2 İK",
                            Email = "hr@test2.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Test2 Personel",
                            Email = "personel@test2.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$fgeAx3QXBTMBAfhNflNjHu2px60jVk65AEwZe7xAA8G5p3.koIWI.",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "Admin",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "HR",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "Personnel",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "Admin",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "HR",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "Personnel",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "Admin",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "HR",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Role = "Personnel",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("20000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.Expense", b =>
                {
                    b.HasOne("ExpenseService.Domain.Entities.User", "RequestedByUser")
                        .WithMany("Expenses")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.ExpenseApproval", b =>
                {
                    b.HasOne("ExpenseService.Domain.Entities.Expense", "Expense")
                        .WithMany("Approvals")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.User", b =>
                {
                    b.HasOne("ExpenseService.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ExpenseService.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExpenseService.Domain.Entities.User", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
